baseURL = 'https://SimpleOpenSource.github.io'
languageCode = 'en-us'
title = 'SimpleOpenSource'
theme = ['SOS']

[menus]
[[menus.main]]
    name = 'Documentation'
    url = 'https://docs.simpleopensource.com'
    weight = 20
